# Generated by Django 2.2.1 on 2019-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefone',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_nasc',
        ),
        migrations.AddField(
            model_name='user',
            name='photoURL',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='providerID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UID'),
        ),
    ]
