# Generated by Django 2.2.1 on 2019-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='aproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reputation',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
