# Generated by Django 2.2.1 on 2019-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190517_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
