# Generated by Django 2.2.1 on 2019-06-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190527_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemplatform',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='itemplatform',
            name='icon',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media', verbose_name='ícone'),
        ),
        migrations.AddField(
            model_name='report',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
