# Generated by Django 2.2.1 on 2019-06-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190610_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemplatform',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemplatform',
            name='icon',
        ),
        migrations.AddField(
            model_name='platform',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='platform',
            name='icon',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media', verbose_name='ícone'),
        ),
    ]
