# Generated by Django 2.2.1 on 2019-06-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190610_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icon',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='ícone'),
        ),
    ]
