# Generated by Django 2.2.1 on 2019-07-12 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190613_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='reputation',
        ),
        migrations.AddField(
            model_name='comment',
            name='changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='core.Driver'),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.Platform'),
        ),
        migrations.AlterField(
            model_name='report',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.Driver'),
        ),
        migrations.DeleteModel(
            name='Reputation',
        ),
    ]
